import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=G_cQYGT-dbYEt1GlmkZ6ZnVBIz-1iLcpptMxc5vZ25mPrYL6ymPH_3cubd_9ub2qAUe4GXGoB5yXCTd_kGsOOKsakpyaW1_-AckRpj09ZQHKLFv1pnivA-RxQoZs31ySSfyI0N9uzgFBK2kloI7dnigxU7rsUaZyJjNVALmFNMYVKsvTFetYvTcrln8Fmiqi_84fQmjazbI4M15rtcfNNmyZU0StaH8BLZYEAShxkinparMPvw49oi-dIera9Uhq-cHZ4z-1J4ZSXDA_8-8sFHPA-1m2L9ntbLXh-mjPKEH_1H_1UezHnX3RuTGjaopYAbNWJYBMucXniR_Cyq1K-4AalH6c5gEHwBjocQYW9N2R6elS3Nw7Uw0b9g7Z6SLaWrTaQouXdEJlIoCrXHamlLtiRiN-l9YzjCXei27dcuUob4y-bxteN_YqT7JylvmiEb0_OZANhTegCEgOKJXW26PLJDw0Qa_SziIn43sX2Y0TgzlHLjPVAlR1GGvv0no9GAvxsMTWO8rvUSXeqQ3fGo_mK8B0iJfqJ6jzjuCxbKh1H2KbPvcRF7KmzJS_OWr2vkQe2WlvlIUsGfsJYVB-g-AATGKo7OdeQ0nl-8O-aUzSUyqdyXVNsBSNTRly0pM4DCyvkrBjCZt-bK_Z-ztlSXvTjbNIOi43rOhMCvWGKMAtK3-yj1uYgPKWVTnEvvK_1TW0MVmEyecXBu0-uFAUeeaNvuCtdnIl8lDBJrIU2nJVlpsU483PeOy0XB17AZsh4pRcwz5Unacakx-qlyIAR_30NMJZDMumle8BxBPCw7y9S2CP10Sa1qdxqw3XTxIuqyRvv_BWwBNJz4q8OcIDVRL2hATeuOABXQvwfkuiQjDhMKUwyBs44JQmO6yFwQF2TT46UAEHuKhB08NDrbDqrSFKLYWFWAAT7rsMevOZghHAKLXsuZAIYMI6l05DoOqJAOJUl04CP1O2ng0uHUNes9aKkOGO1u-_YOkDmJDWEdWI0QQlPrZ0-Nnz-UOYi1y3WIIe3MeHaYud8DWW_ajbDZB-nGGRcxlnDsZimgulSZZhocLeRG6Vm1bLs_gEHghXwzlDXDRuzxLGpUxuHWpYouFCtsX6xJ_hBONmUcqwU25EHmpYkp70QIvN8jMQml7D7ghYlI66uP0WeDQr3guWTTsqTRaCBLBUNPmBsNMjNu0Uk63GSKgLwz7-YS3aCN4Q3juc5x-kooE2SSbrHP-wEw080wrcCJGgoOZWG7aMlALHYzgrOKFxDwjajgMOayS2n95xgMO1BVX0jJB72IfVwVpqIOvNh2DCLa0XBCOJwktp0RG_vVMjW68HvaLF0HqnNoK3lIRgcLgkQVITVFGtbFFKfe-eiYeMHs_VxjlGVz6byawB

export const ef2HectorAnim: WaapiEntity[] = [
  {
    type: 'ring',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '34.17%',
        top: '50.17%',
        width: '7.83%',
        height: '7.83%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: 'transparent',
        boxSizing: 'content-box',
        borderWidth: '6.53cqi',
        borderColor: '#64afff8c',
        offset: 0,
      },
      { opacity: 0, offset: 0.05 },
      { opacity: 1, offset: 0.08 },
      { borderColor: '#64afff8c', offset: 0.33 },
      { borderColor: '#45cafd7d', offset: 0.37 },
      { borderColor: '#99e3ff7d', offset: 0.42 },
      { borderColor: '#99e3ff7d', offset: 0.43 },
      { borderColor: '#34c7ff7d', offset: 0.47 },
      { borderColor: '#34c7ff7d', offset: 0.52 },
      { borderColor: '#78d9ff7d', offset: 0.53 },
      { borderColor: '#78d9ff7d', offset: 0.57 },
      { borderColor: '#3cc9ff7d', offset: 0.62 },
      { opacity: 1, offset: 0.72 },
      { opacity: 0, offset: 0.75 },
      { offset: 1, opacity: 0, borderColor: '#3cc9ff7d' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '34.17%',
      top: '50.17%',
      width: '7.83%',
      height: '7.83%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: 'transparent',
      boxSizing: 'content-box',
      borderWidth: '6.53cqi',
      borderColor: '#64afff8c',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '63%',
        top: '50.17%',
        width: '11.66%',
        height: '11.66%',
        rotate: '0deg',
        outlineWidth: '0.67cqi',
        outlineOffset: '-0.33cqi',
        outlineStyle: 'solid',
        borderRadius: '50%',
        backgroundColor: '#ffffff00',
        outlineColor: '#ffe300',
        offset: 0,
      },
      { opacity: 0, offset: 0.13 },
      { opacity: 1, offset: 0.17, outlineColor: '#ffe300' },
      { outlineColor: '#ffeb00', offset: 0.23 },
      { outlineColor: '#ff9700', offset: 0.25 },
      { outlineColor: '#fff300', offset: 0.3 },
      { outlineColor: '#ffb500', offset: 0.33 },
      { outlineColor: '#ffe300', offset: 0.37 },
      { outlineColor: '#ffe300', offset: 0.4 },
      { outlineColor: '#ffbd00', offset: 0.42 },
      { outlineColor: '#ffbd00', offset: 0.45 },
      { outlineColor: '#ffe300', offset: 0.47, opacity: 1 },
      { opacity: 0, offset: 0.5 },
      { offset: 1, opacity: 0, outlineColor: '#ffe300' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '63%',
      top: '50.17%',
      width: '11.66%',
      height: '11.66%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#ffffff00',
      outlineColor: '#ffe300',
    },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '63%',
        top: '48.67%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '63%', offset: 0.53, top: '48.67%' },
      { left: '64.83%', offset: 0.67, top: '57%' },
      { offset: 1, left: '64.83%', top: '57%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '63%',
      top: '48.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '60.83%',
        top: '49.83%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '60.83%', offset: 0.53, top: '49.83%' },
      { left: '56.33%', offset: 0.67, top: '34.67%' },
      { offset: 1, left: '56.33%', top: '34.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '60.83%',
      top: '49.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '62.5%',
        top: '50.67%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '62.5%', offset: 0.53, top: '50.67%' },
      { left: '66.33%', offset: 0.67, top: '44%' },
      { offset: 1, left: '66.33%', top: '44%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '62.5%',
      top: '50.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '62.17%',
        top: '51.33%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '62.17%', offset: 0.53, top: '51.33%' },
      { left: '56%', offset: 0.67, top: '65.33%' },
      { offset: 1, left: '56%', top: '65.33%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '62.17%',
      top: '51.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '33.67%',
        top: '50.17%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '33.67%', offset: 0.8, top: '50.17%' },
      { left: '35.83%', offset: 0.93, top: '56.67%' },
      { offset: 1, left: '35.83%', top: '56.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '33.67%',
      top: '50.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '35.67%',
        top: '49.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '35.67%', offset: 0.8, top: '49.5%' },
      { left: '36%', offset: 0.93, top: '44.5%' },
      { offset: 1, left: '36%', top: '44.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '35.67%',
      top: '49.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '34.17%',
        top: '48.67%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '34.17%', offset: 0.8, top: '48.67%' },
      { left: '43.83%', offset: 0.93, top: '35.5%' },
      { offset: 1, left: '43.83%', top: '35.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '34.17%',
      top: '48.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '34.67%',
        top: '50.83%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '34.67%', offset: 0.8, top: '50.83%' },
      { left: '43.83%', offset: 0.93, top: '64.5%' },
      { offset: 1, left: '43.83%', top: '64.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '34.67%',
      top: '50.83%',
      rotate: '0deg',
    },
  },
]
