import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=G6ZYIqpH2YiKzXiEozBuuIOP9XFSluVIscbIJef_jLNB_FukI19f6OQRSHI8p128UK5K89_mfyZ_pvbWVV-VOQS8GiNAkAgEq3CCxSDg4VKXlekbE03qshJbbCd67lv71fleAl495C-e4bed0MgnOouINUJy3QNPKqVRed1bpId7RCJWLf-1-IiJugwHEBFi154zC-n-e0bAN1JGfmJishFp3_b-yJyl3LNDhS6WCcZUreHhr_AfY6V94G6SmvQ4v8OAIAhte-O2IXWR0Pc_dXVwX2yKjZ__qWX6zGLUu9yUBsrlBZD4l2e-W1zrp2Kl5bErTq6x_ItXxedAS-vyYnrtqrfYKBgjluf1a8_B269wa_S5rg39Vndl-Zi_NXp1Li4KfiZ0ZV5k8c6_qmbVXbepi6L4hZSwzzUWBdH_1vrXp0DU6y2zb5htHz7skrdlALtDEuUlIRxGA_csy-HuI97DU-IeLEPYA8shGwRW_3TIY3pbhV_9z5eu2a9C33qEL0y85i1O2A2CgHx503PdaPy3Z8nl5-C5bnTuA4r3R_sevcfPX9nCDBvPdRF_1PcBxcdvhUy6vMq-9PuPSnL4EgP8DiP6sz1ng_fWN2LbYk_fmfYHGyjBghh2tq03btzKCTySlZPS5f-c_eezrz-qWnHhPcllvz37G3_2y094vaXOlo6OX_bbs7Sl_Ff-NSr5HaENL2o0o7X8T94rtEbb88Tkf_z58-AlT7ez5rkrIj_0X4Of_0nt8_rUHjgHp3Z_a9TauuKK3nvdJfrjKR0D1Q6bKrDSluMzW0K782CCL_iVHY8dec7A8FGOpwDXa8czwx31o8nWUPPxqZjYZ_IFbQ63rv1_dboib6DqlKe2_qEd0OT2CL73LWnQvz8nVpfn9eCILh8urOgz6I5y_McG1ypHM9_viFxEWyOk_SwyvZ9OmxbdSQ0dbvgmaTl-wWJsG_rlm1_Rr13w9LXGxCXvma524ddaL0BCH93WzZlSD9FzLl09pFAW39e_qo2qb7dNde2-wjlw-cpT-NaJHC_f2PegVK6lx68sgON32UvkHus-tZdJzo9qmhukimnPpNCv7xiFbJCwcy6n9vkDg-jEM1q3LXRnx6j4qAdcZyYxF8KqBsqmw2c8c6SJFDPncmr_gzRl7MmZntovEQMTq8j7mxQqBq-arvcloSj2oiozNCIpbPaauZ_Se2NCSewZLhO9q6Rw7mMLL5QzCRyOyE-MkW7moBM6aP8wxIruO-doGTCYIFj4tKvrbA7MQ3JyFyQgVJ46z3KBtVLufuNqkU36QBBKfL8Ht5qPu350_e7I5n4e0kDvcnruS8qVCDsDH0a9NZ45Bhk0kecqKT_EELbMwHe5mq5iTGnLce4RjJBTdd_dqn7cve0SOzZbjpdtiZof3dj5YPJmPP9TW91yc7-P1eD5jnbAT3Qodo0nXT430tq6YsaEtzRpuDroBTElweAd3V3GZAKDB6OhHLf9GVxaYv24Qc_gljJi41Y6QylO9Cqjnj_3vufvfLv0Xa3ktekiw3gkm83sjOMpLeGDmNonbY21S9PCwVOJlCaKDKcOKe4UGMvAW98QVmtkKvBaueA2euDJEdTTQX79O3679JDzurAoPbV0lJGvAnj0akOkNYVGkrW4rjE8EqaRsObwlNYM16T20oWSeD2x41Zq1JTssjEBUoM5xMvAL3Qx1l4VJWvOa2U2MTl48r1WKCAnXPANW7oXwjSXWj7KPrsv4CkREHC4dJF7JScLlVSipiQvlmjqkGKxVYQMvIaS83KFqSi8VhLhxoPndS16VtYN2urhIFI8EuXtBh6JWH2uqeSRjTFm4ZESOwvhKa3JCZbaSxeXRGktrOJUoqY0ZAGUOqRoxXSZgSc2-g3iasdGKF4ruTiIIk9prRVjbr3AWkdxtm5DTSkN1yqIS5WZxdTTxtPz2pEvvO_1dLz_kVaQY8ma4NmpbXhML0Fd28KLnX18CkHn5mdUBab1eeakMWUH_HH6bDLl6rqjWwDMuF46UrnrVGBPZ0I-DF0ATOMGF4Qxc9fvlunkZqkxAcHCtQeEaEiWrN8rU6eDsnL2fU7HT0fHIKMsZgr7nTKttkgu1SGIja9IlHDo382gQSxNQBAr-mE-k2Nuvbs22d-E5mSSrB-r9WrFYTH13W3L_q6mco-IQW_6nE6bRUzk95eTVaaTTBV1NwXRSbDgYulDvy0r12E60yKCWE3uuaRQTPunq_1nys_6MSgLLLOiZA1E2spXfbtkP9p_p_DSdEACS61kCtrptmX_F6ttOYZlapKKOUhgaTcM3YxFctwV1lrel7BFLCsboXVHUq1YiDUCT6S-FmuXRjDJL2zCTbxUW_v18k7mHmpKnUW9cQsphQFTuYMU0SEgi-oa7o0VyWHMCl4r-xkpwiPVYX6AJ6MpueZPz2vV0-PlX78WQtX9Pc57OxK2Qam969eZVoG1gXhGkrpwyXh1A4DpRcF3pJ1FxCEg6ccOpLA3fRDMdLsi6ylV4NX927m76sfWJvcwOXKN4vSzK6OU-Z3lIEWcV8LIy56XpPjZz58X5dNbQiDOyROv9S34ZYXw7599_ZH_apGaEq2om-D-iuKNKjO253mMBzkdPx-mM7mEKgTK7q_l3eKZNEMJTXB_7e_GypoMYjLNt3_2SyHgoVa0vdxfdbuRutKOUu9zf5Xuhhjgs1EkiSqdb1Teawd67H7kT6nTqGt1E9xfT7uxIlTBnEhynMYGityhB187ruFfOOU04CV47YsxRIRHHmJjCE9WUfsE5NILL6glPPdM91BTmqfAdwsp9WgscAcpNkNxWVTXCNs4GcLhBF77gSY7AI0UYpyCZxZWhHXP9iu7gol0kA8GEqhDRJOmYbebtSWmgzkIJDPbaoPcmUCQPBdj7QYNBmTGSnD9dgGqkJl1M9oOyFGHzJAILw4kMCACxUok9gfLzBJswYyNvqorEEgIDqFbZv_VIo-siwlBTLPSLFa9_t20krM9_APZuz-z0tG0qN-WFafH7GFZl64QBxtIDXYc6RYA658JDM6ogEhgzwiMGs4-99uy7txl8jLsY0-labklYxvYM1Nmvy5aBySwYRHvttLebctOYuo2s7Ltx7SaZel-RBBL52MxGjUp-wm0f080tTM9xfcxXaqzUo8b17ozUyV0rwfB_pFX-iBrWTuwqjQcj7G4AJh-wu_EZC8fL2S7vEjczPpI3Wrsb0_EsCv1fDHs8qI-io1EuwN2QlOdMQN32wCHJelo2RvTBjhASIXZrKINsKueevBQoQ2w1ywVBxAgeBAcR61slDXWrcYRzcpIKzskUfdfjyzLXj6IgWm9H3RO48uiwcXzbu65swLaSJHxdqZeAO4MfO1u_38--4ZCvqbNTMaDBHb7GVskk_g0q5AsAnU3p6q2ah-8AHBKJHnc2oQi8_2S7efOwJ0vrfw7e6PY0upc3c_ncr8V9X61g8SsvE_o_WaiJ58uxLM4EYeypuaTLMwSm9EN3uEp2laAjH-wDQ9Wo4Avea00XS6HR_aAmsJTSmY25-alFw0KS4mpi-6hpiS7cuoWUnJ6o8gdpNhTO2hRXSMd_EkPV3x4rRyb-wM8UmiYGJ6JuZ1DDSqqdkkoIUQd5dViIe-Jj26wlXkxi7lVrzNghU8L32ncbQO8AqSaw4q0AbbFaUcCU9oAm5mUkkYbWHVhCHrQJQsOgqwMHccnY5xPEgp4ireU2CwB2zvpczfYoE5PGFY-iS9BI3z_P7bYQuqGw0rdBthLrE6TzMri6-DO9cG-7fsWwsG1IUsL4VichpEWHJxX2nAhHByLh9VCODakTb8BBzfqrFkIB1cjQVsIxyqMQDfhyJltGhuy1QWUGbxWBnqu8HhyLZIzvBKF8ksfe_FRAMl3eOb1fCWGSpMw0KGiSvVL18hfrpauS4j4s5LYVAM8GaYJgueOumVjZz3i3QOPwr4cS-kRH69GazU2zyP42NvtYrM8whfi5ufAxCryRcCMYzs8gvewBREb4CE-HMBkrHhHKO39fpQS37soeTEzSYhnSh1UF9OhkhM7dDJ0m4AhFaFU9Wd-IlTaBAcvDSrNApxPgn7MeQj-j0yLfyXdZ6tx3AsygmtIlcYNHyN4hilI3NExgpcx5sdtGyPOeq7NlnFdxgg-T7Zw3Hsxgvvs0Ih7K0YoMQrVSYl_c5YEMHIS4pkSIZdkOlTS_UEnGSoBC2xSodLCKMpEqORpYJkGldBdbSZB_4vc4Q8o3weXiU4EahQ3BYzgTnMQYus_ghdusYvV_ggeL6F9rO5HnPUEoEms50fweGFisX4fwQc2EcSKfYQSvHX8lPiLTInmEiQhninZWQKkQyWgsFAyVCIXbJIKlbSZAiVCpTkWQWlQKVppRRLk1nhtxb0AI77TO5ssBzHsH3HWYcrLYpo_guvrgI2R_QjeM6BdrORHcNHWSmPuPoJD8YEUc_URvL_dwjE7H6GUuYSQEp9nSjIjwgnxTEmseqN0qERh4yIZKgnQOk-FXm_OColQiZ-7fho0644YLwn67epAmT3uP3oJ

export const efRaidplanAnim: WaapiEntity[] = [
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '3.7%',
        height: '3.7%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '4.67%',
        top: '6.33%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#68046a',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.09 },
      { opacity: 1, offset: 0.11 },
      { opacity: 1, offset: 0.18 },
      { opacity: 0, offset: 0.2 },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.44 },
      { opacity: 1, offset: 0.53 },
      { opacity: 0, offset: 0.56 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '3.7%',
      height: '3.7%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '4.67%',
      top: '6.33%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#68046a',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '12.67%',
        top: '6%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#68046a',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.09 },
      { opacity: 1, offset: 0.11 },
      { opacity: 1, offset: 0.18 },
      { opacity: 0, offset: 0.2 },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.44 },
      { opacity: 1, offset: 0.53 },
      { opacity: 0, offset: 0.56 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '12.67%',
      top: '6%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#68046a',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '3.7%',
        height: '3.7%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '20.5%',
        top: '6.17%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#68046a',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.09 },
      { opacity: 1, offset: 0.11 },
      { opacity: 1, offset: 0.18 },
      { opacity: 0, offset: 0.2 },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.44 },
      { opacity: 1, offset: 0.53 },
      { opacity: 0, offset: 0.56 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '3.7%',
      height: '3.7%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '20.5%',
      top: '6.17%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#68046a',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '3.7%',
        height: '3.7%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '16.17%',
        top: '6.33%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#f503fa',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.22 },
      { opacity: 1, offset: 0.29 },
      { opacity: 0, offset: 0.31 },
      { opacity: 1, offset: 0.33 },
      { opacity: 1, offset: 0.4 },
      { opacity: 0, offset: 0.42 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '3.7%',
      height: '3.7%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '16.17%',
      top: '6.33%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#f503fa',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '3.7%',
        height: '3.7%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '8.67%',
        top: '6.17%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#f503fa',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.22 },
      { opacity: 1, offset: 0.29 },
      { opacity: 0, offset: 0.31 },
      { opacity: 1, offset: 0.33 },
      { opacity: 1, offset: 0.4 },
      { opacity: 0, offset: 0.42 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '3.7%',
      height: '3.7%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '8.67%',
      top: '6.17%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#f503fa',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '12.5%',
        top: '6.17%',
        rotate: '45deg',
        outlineWidth: '0.33cqi',
        outlineOffset: '-0.17cqi',
        outlineStyle: 'solid',
        backgroundColor: '#f503fa',
        outlineColor: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0 },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.22 },
      { opacity: 1, offset: 0.29 },
      { opacity: 0, offset: 0.31 },
      { opacity: 1, offset: 0.33 },
      { opacity: 1, offset: 0.4 },
      { opacity: 0, offset: 0.42 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '12.5%',
      top: '6.17%',
      rotate: '45deg',
      outlineWidth: '0.33cqi',
      outlineOffset: '-0.17cqi',
      outlineStyle: 'solid',
      backgroundColor: '#f503fa',
      outlineColor: '#ffffff',
    },
  },
  {
    type: 'triangle',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fill: '#90cfff7a',
        position: 'absolute',
        translate: '-50% -50%',
        left: '27.33%',
        top: '50.5%',
        width: '13.33%',
        rotate: '90deg',
        scale: '2.12 2.12',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { opacity: 0, offset: 0.6, left: '27.33%', top: '50.5%', rotate: '90deg' },
      { left: '33.89%', offset: 0.61, top: '34.16%', rotate: '135deg' },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { opacity: 0, offset: 0.71, left: '33.89%', top: '34.16%', rotate: '135deg' },
      { left: '50.11%', offset: 0.72, top: '27.41%', rotate: '180deg' },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { opacity: 0, offset: 0.82, left: '50.11%', top: '27.41%', rotate: '180deg' },
      { left: '33.9%', offset: 0.83, top: '34.16%', rotate: '135deg' },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { opacity: 0, offset: 0.93 },
      { offset: 1, opacity: 0, left: '33.9%', top: '34.16%', rotate: '135deg' },
    ],
    initialValues: {
      opacity: 0,
      fill: '#90cfff7a',
      position: 'absolute',
      translate: '-50% -50%',
      left: '27.33%',
      top: '50.5%',
      width: '13.33%',
      rotate: '90deg',
      scale: '2.12 2.12',
    },
  },
  {
    type: 'triangle',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fill: '#90cfff7a',
        position: 'absolute',
        translate: '-50% -50%',
        left: '73.33%',
        top: '50.5%',
        width: '13.33%',
        rotate: '-90deg',
        scale: '2.12 2.12',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { opacity: 0, offset: 0.6, left: '73.33%', top: '50.5%', rotate: '-90deg' },
      { left: '66.42%', offset: 0.61, top: '66.69%', rotate: '-45deg' },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { opacity: 0, offset: 0.71, left: '66.42%', top: '66.69%', rotate: '-45deg' },
      { left: '50.11%', offset: 0.72, top: '73.41%', rotate: '0deg' },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { opacity: 0, offset: 0.82, left: '50.11%', top: '73.41%', rotate: '0deg' },
      { left: '66.42%', offset: 0.83, top: '66.69%', rotate: '-45deg' },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { opacity: 0, offset: 0.93 },
      { offset: 1, opacity: 0, left: '66.42%', top: '66.69%', rotate: '-45deg' },
    ],
    initialValues: {
      opacity: 0,
      fill: '#90cfff7a',
      position: 'absolute',
      translate: '-50% -50%',
      left: '73.33%',
      top: '50.5%',
      width: '13.33%',
      rotate: '-90deg',
      scale: '2.12 2.12',
    },
  },
  {
    type: 'triangle',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fill: '#90cfff7a',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.17%',
        top: '73%',
        width: '13.33%',
        rotate: '0deg',
        scale: '2.12 2.12',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { opacity: 0, offset: 0.6, left: '50.17%', top: '73%', rotate: '0deg' },
      { left: '34.13%', offset: 0.61, top: '66.22%', rotate: '45deg' },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { opacity: 0, offset: 0.71, left: '34.13%', top: '66.22%', rotate: '45deg' },
      { left: '27.62%', offset: 0.72, top: '50.24%', rotate: '90deg' },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { opacity: 0, offset: 0.82, left: '27.62%', top: '50.24%', rotate: '90deg' },
      { left: '34.13%', offset: 0.83, top: '66.22%', rotate: '45deg' },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { opacity: 0, offset: 0.93 },
      { offset: 1, opacity: 0, left: '34.13%', top: '66.22%', rotate: '45deg' },
    ],
    initialValues: {
      opacity: 0,
      fill: '#90cfff7a',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '73%',
      width: '13.33%',
      rotate: '0deg',
      scale: '2.12 2.12',
    },
  },
  {
    type: 'triangle',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fill: '#90cfff7a',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.17%',
        top: '27.5%',
        width: '13.33%',
        rotate: '-180deg',
        scale: '2.12 2.12',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { opacity: 0, offset: 0.6, left: '50.17%', top: '27.5%', rotate: '-180deg' },
      { left: '66.3%', offset: 0.61, top: '34.05%', rotate: '-135deg' },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { opacity: 0, offset: 0.71, left: '66.3%', top: '34.05%', rotate: '-135deg' },
      { left: '73.11%', offset: 0.72, top: '50.24%', rotate: '-90deg' },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { opacity: 0, offset: 0.82, left: '73.11%', top: '50.24%', rotate: '-90deg' },
      { left: '66.3%', offset: 0.83, top: '34.05%', rotate: '-135deg' },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { opacity: 0, offset: 0.93 },
      { offset: 1, opacity: 0, left: '66.3%', top: '34.05%', rotate: '-135deg' },
    ],
    initialValues: {
      opacity: 0,
      fill: '#90cfff7a',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '27.5%',
      width: '13.33%',
      rotate: '-180deg',
      scale: '2.12 2.12',
    },
  },
  {
    type: 'melee',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '62.67%',
        top: '63.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '62.67%', offset: 0.13, top: '63.5%' },
      { left: '61%', offset: 0.2, top: '61.17%' },
      { left: '61%', offset: 0.69, top: '61.17%' },
      { left: '66.83%', offset: 0.76, top: '66.67%' },
      { offset: 1, left: '66.83%', top: '66.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '62.67%',
      top: '63.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '37.33%',
        top: '63.67%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '37.33%', offset: 0.13, top: '63.67%' },
      { left: '39.17%', offset: 0.2, top: '61.33%' },
      { left: '39.17%', offset: 0.69, top: '61.33%' },
      { left: '33.5%', offset: 0.76, top: '66%' },
      { offset: 1, left: '33.5%', top: '66%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.33%',
      top: '63.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '63%',
        top: '37.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '63%', offset: 0.13, top: '37.5%' },
      { left: '61%', offset: 0.2, top: '39.67%' },
      { left: '61%', offset: 0.69, top: '39.67%' },
      { left: '67.33%', offset: 0.76, top: '34.17%' },
      { offset: 1, left: '67.33%', top: '34.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '63%',
      top: '37.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '37.5%',
        top: '37.33%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '37.5%', offset: 0.13, top: '37.33%' },
      { left: '39.17%', offset: 0.2, top: '39.33%' },
      { left: '39.17%', offset: 0.69, top: '39.33%' },
      { left: '33.17%', offset: 0.76, top: '33.5%' },
      { offset: 1, left: '33.17%', top: '33.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.5%',
      top: '37.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '68.33%',
        top: '50.83%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '68.33%', offset: 0.13, top: '50.83%' },
      { left: '79.33%', offset: 0.2, top: '50%' },
      { left: '79.33%', offset: 0.69, top: '50%' },
      { left: '63.17%', offset: 0.76, top: '50.5%' },
      { offset: 1, left: '63.17%', top: '50.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '68.33%',
      top: '50.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '31.33%',
        top: '50.67%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '31.33%', offset: 0.13, top: '50.67%' },
      { left: '21.17%', offset: 0.2, top: '50.17%' },
      { left: '21.17%', offset: 0.69, top: '50.17%' },
      { left: '39%', offset: 0.76, top: '50.33%' },
      { offset: 1, left: '39%', top: '50.33%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '31.33%',
      top: '50.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.33%',
        top: '31.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '50.33%', offset: 0.13, top: '31.5%' },
      { left: '49.83%', offset: 0.2, top: '21.83%' },
      { left: '49.83%', offset: 0.69, top: '21.83%' },
      { left: '50.33%', offset: 0.76, top: '38.5%' },
      { offset: 1, left: '50.33%', top: '38.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.33%',
      top: '31.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 9000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.17%',
        top: '68%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '50.17%', offset: 0.13, top: '68%' },
      { left: '50.67%', offset: 0.2, top: '77.83%' },
      { left: '50.67%', offset: 0.69, top: '77.83%' },
      { left: '50.17%', offset: 0.76, top: '61.17%' },
      { offset: 1, left: '50.17%', top: '61.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '68%',
      rotate: '0deg',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '22.67%',
        top: '70.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '22.67%',
      top: '70.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '20.83%',
        top: '69.17%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '20.83%',
      top: '69.17%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '25.17%',
        top: '27.33%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '25.17%',
      top: '27.33%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '23.33%',
        top: '25.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '23.33%',
      top: '25.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '70%',
        top: '26.5%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '70%',
      top: '26.5%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '68.33%',
        top: '24.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '68.33%',
      top: '24.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '72.33%',
        top: '74.17%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '72.33%',
      top: '74.17%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '70.67%',
        top: '72.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.64 },
      { opacity: 1, offset: 0.67 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '70.67%',
      top: '72.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '46.17%',
        top: '13.17%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '46.17%',
      top: '13.17%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '44.67%',
        top: '11.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '44.67%',
      top: '11.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '46.17%',
        top: '84.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '46.17%',
      top: '84.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '44.67%',
        top: '83%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '44.67%',
      top: '83%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '84.5%',
        top: '44.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '84.5%',
      top: '44.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '83%',
        top: '43%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '83%',
      top: '43%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '11.67%',
        top: '45.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '11.67%',
      top: '45.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '10.33%',
        top: '44.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.53 },
      { opacity: 1, offset: 0.56 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '10.33%',
      top: '44.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '17.17%',
        top: '46%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '17.17%',
      top: '46%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '52%',
        top: '13%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '52%',
      top: '13%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '50.33%',
        top: '11.17%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '50.33%',
      top: '11.17%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '52%',
        top: '84.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '52%',
      top: '84.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '50.17%',
        top: '83%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '50.17%',
      top: '83%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '90%',
        top: '44.83%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '90%',
      top: '44.83%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '88.33%',
        top: '43%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '88.33%',
      top: '43%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '15.33%',
        top: '44.17%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.76 },
      { opacity: 1, offset: 0.78 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '15.33%',
      top: '44.17%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'M' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '28.67%',
        top: '71%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '28.67%',
      top: '71%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '31.17%',
        top: '27.67%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '31.17%',
      top: '27.67%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '29.67%',
        top: '25.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '29.67%',
      top: '25.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '75.83%',
        top: '26.33%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '75.83%',
      top: '26.33%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '74.5%',
        top: '24.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '74.5%',
      top: '24.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'rect',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '78%',
        top: '74.17%',
        rotate: '0deg',
        backgroundColor: '#000000',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '78%',
      top: '74.17%',
      rotate: '0deg',
      backgroundColor: '#000000',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '76.5%',
        top: '72.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '76.5%',
      top: '72.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
  {
    type: 'text',
    duration: 9000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '4.17cqi',
        position: 'absolute',
        left: '27.17%',
        top: '69.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.87 },
      { opacity: 1, offset: 0.89 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '4.17cqi',
      position: 'absolute',
      left: '27.17%',
      top: '69.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'R' },
  },
]
