import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=GwggAGQot4xU_Sn2XYESgfMY0m0wOw0wAxGDAJmqPLu_O1-V57mEMzX_v-U7u_k3FYRczlAUEiE3rUnqL2Opx7P7YA6b2iRfURSoyOVNKK3coVSPjUUiLEKpCImMrZXeqlfTCiJWdPLK3KlZTtmvhP7NqUmg25Itgea7nu1nhqXqaErJEqM2MsGk3ZBEvaaCaWFTVtOPjeWwevPChJERprHRtPrbqX0VgqpSokgOOe5PQ6iLbZ1sGHYan3vumut2e7aR8SidLWDPl4vYaJjWe-uosNvb5_X2-PzuvjXsOzO7cVe0JNbM7Q5QFJt2a25ptxspCW0LwQF4uC7GDyH3x03s4criFCuUKH5ntAEqtsAdX9xFUZCq5q0Enjk2lntPbpf_v-3QR-H58WKYvvfl3clvzu5K_93j-95Yc6U5eondMBQwlg9HZ67ZL-BGPIGykUPoxl_kfjSEGs4ljx61vtFicpIjGr64Mx9e9vrh63bbwaEazg8n3B365jRs8kQcrxLEj49XpEal4MCzOLEPYitJlYz1w-MNsSq1ms9dQ_7iv3Ph8OJvB0ACRMLTcb9wNki7Hpp2X5O8d1baQQyj5htM7zTfEPAqLUPHnuUutm1OSv8x8sT0-TqFMJD6zBbgBzk2NHy-LGzEkSvJnIhsYg8nPpzshRVOyEOnpLqhZezYKRSt741pQAVb8_lrsKpaWo-xna3GNTvrjZExTXRlpq_fw1ShzRjVymdLTGlzj9qxwx6yR8Y15tuoztPu6-jOqmhWrDM1iaoB1rUva4ttctbJnqA6EFXQGBlsSzxP4qNDjegM3Z52XdezqVjgCCIf7eh6iRNtfBz3axdNp9658yfKtA96ueT8cSfNEynxiGxu9b2CPfyVCoTQS1x0PxhC1nHjja3sbyb2BYKgDOGKZZ-HsHp9jLPieqfRyU6cYMByF-usPf2drTbTkKNPnrT7qft0ve1eoE2PwLuRIEq9zX3LJ3734BTu7HItug4dKR2cvbSB0zTx5yHnuWsK2Ddnd96dGkLPXSNcenmFEGQ-n53SQefnifnkuEj6D0IWtlCrphSAYEPUxgG2JM7WVVYxBwfmUFTbT0N1elk9aksaeO7qr26-m7llbJhhxEN8QCoI0rUAkACmHIkFRdFeCxyQOSSJtUAMo37UgbgiyTmKEQEjmYxGy6cFyYfYgFxaEAGPNOTRguUsIy3H3JAj-swv_jvBShczVsKRxYgsOkIIxEFiVB4NZtzXHCEUb0QkHTNsME5GHBCdxVcsg4RDRdFB9MBmUyOqvOgUauB1E4GJgGgIekCg0XIpkVJdQAiXTbBi9eYohPiCHJK9wqFjhpWEvzFZtDqLJq1lGBp6sagNOAZdQLAPkW6k_foTVjFIcdZJH4HBbJvq5Njxv6oRAda-Aq75rIIQiNu1aM4ogDVlA3id0nMjZIuJ5T4dkCJ4Uc1YHXCE4tFgPVPoQfJGTLM64CgxOxS0OmAZUzkuZYshFi8RtUY6JUoHLCfNfJokVDHDy4Fx2qxUyuNLmOAUTbeyGkEHCDHCS2SrLGh8J0QurJliIG6CfCcsnRh9ZYhBk2syPumSqGtduIYvxXnpYOiBjabcLBekz6AnBE-ljNMWS1-DkkhD9UIHpIiRZZyTqorC11Tf347YLiCYwSTem4v06X_du7EucIk2S4ZJ1yESQHlRkM1JpWaGb6imwwHbOcLtwQ5VtBLXQQCJ5gQBnrqA8ADRD7V6c4SuBsDTRCFTllEBvx0YCQLuYV5FF21cCo8RTbMiQ5U-RAb3a7QM9fnAoLDFy0iZD0K1ZDEjh8RAv2tWj2DuxeTBpDz-xCzWKebl8gQRbDouny8CdbPEZfMbeCoh2kyqYYIEcqW7jAyLoNhz8NSgO6LpAMEMNNu-A8qGAzaXFTjC6gDBDjR7xWqT7wCjbIxDoAOEcFgE1ZwmXuA0ckIbRO0o9hyrAsu1EGoPmz0QKuNqPO9Cgi9ekYzUWzb3fbhlTKgmikONVKAe1fBqyAGDFI_EsgQdoPMrJ6utxlhBvgw

export const rb3HectorAnim: WaapiEntity[] = [
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '40.17%',
      top: '45.83%',
      width: '13.33%',
      rotate: '112.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '54.17%',
      top: '40%',
      width: '13.33%',
      rotate: '-157.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '19.5%',
      top: '63.67%',
      rotate: '62.28deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.5%',
      top: '19%',
      rotate: '157.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '81.17%',
      top: '37.33%',
      rotate: '-112.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '63.17%',
      top: '81.83%',
      rotate: '-22.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '61.17%',
        top: '54.5%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '61.17%', offset: 0.3, top: '54.5%' },
      { left: '56.33%', offset: 0.4, top: '63.33%' },
      { offset: 1, opacity: 1, left: '56.33%', top: '63.33%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '61.17%',
      top: '54.5%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '55.5%',
        top: '38.5%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '55.5%', offset: 0.3, top: '38.5%' },
      { left: '64.33%', offset: 0.5, top: '55.67%' },
      { offset: 1, opacity: 1, left: '64.33%', top: '55.67%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '55.5%',
      top: '38.5%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '35.5%',
        top: '43.83%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '35.5%', offset: 0.3, top: '43.83%' },
      { left: '43.5%', offset: 0.4, top: '35%' },
      { offset: 1, opacity: 1, left: '43.5%', top: '35%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '35.5%',
      top: '43.83%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '45%',
        top: '61.83%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '45%', offset: 0.3, top: '61.83%' },
      { left: '44.5%', offset: 0.4, top: '62.83%' },
      { offset: 1, opacity: 1, left: '44.5%', top: '62.83%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '45%',
      top: '61.83%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '46%',
        top: '60.17%',
        width: '13.33%',
        rotate: '22.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '46%',
      top: '60.17%',
      width: '13.33%',
      rotate: '22.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '45.67%',
        top: '39.83%',
        width: '13.33%',
        rotate: '157.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.67%',
      top: '39.83%',
      width: '13.33%',
      rotate: '157.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '60.5%',
        top: '54.67%',
        width: '13.33%',
        rotate: '-67.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '60.5%',
      top: '54.67%',
      width: '13.33%',
      rotate: '-67.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '54.33%',
        top: '60.67%',
        width: '13.33%',
        rotate: '-22.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '54.33%',
      top: '60.67%',
      width: '13.33%',
      rotate: '-22.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'melee',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '61.17%',
        top: '54.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '61.17%', offset: 0, top: '54.5%' },
      { left: '61.17%', offset: 0.3, top: '54.5%' },
      { left: '56.33%', offset: 0.4, top: '63.5%' },
      { offset: 1, left: '56.33%', top: '63.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '61.17%',
      top: '54.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '45.5%',
        top: '62%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '45.5%', offset: 0, top: '62%' },
      { left: '45.5%', offset: 0.3, top: '62%' },
      { left: '44.33%', offset: 0.4, top: '62.83%' },
      { offset: 1, left: '44.33%', top: '62.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.5%',
      top: '62%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '35.67%',
        top: '44%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '35.67%', offset: 0, top: '44%' },
      { left: '35.67%', offset: 0.3, top: '44%' },
      { left: '43.33%', offset: 0.4, top: '34.83%' },
      { offset: 1, left: '43.33%', top: '34.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '35.67%',
      top: '44%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '55.5%',
        top: '38.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '55.5%', offset: 0, top: '38.5%' },
      { left: '55.5%', offset: 0.3, top: '38.5%' },
      { left: '64.33%', offset: 0.5, top: '55.83%' },
      { offset: 1, left: '64.33%', top: '55.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '55.5%',
      top: '38.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '67%',
        top: '43.83%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '67%', offset: 0, top: '43.83%' },
      { left: '67%', offset: 0.3, top: '43.83%' },
      { left: '76%', offset: 0.4, top: '40.83%' },
      { offset: 1, left: '76%', top: '40.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '67%',
      top: '43.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '34%',
        top: '56.33%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '34%', offset: 0, top: '56.33%' },
      { left: '34%', offset: 0.3, top: '56.33%' },
      { left: '24.17%', offset: 0.45, top: '60.5%' },
      { offset: 1, left: '24.17%', top: '60.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '34%',
      top: '56.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '45.17%',
        top: '39%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '45.17%', offset: 0, top: '39%' },
      { left: '45.17%', offset: 0.3, top: '39%' },
      { left: '39.17%', offset: 0.45, top: '26.17%' },
      { offset: 1, left: '39.17%', top: '26.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.17%',
      top: '39%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '54.17%',
        top: '61.33%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '54.17%', offset: 0, top: '61.33%' },
      { left: '54.17%', offset: 0.3, top: '61.33%' },
      { left: '60.17%', offset: 0.45, top: '74.17%' },
      { offset: 1, left: '60.17%', top: '74.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '54.17%',
      top: '61.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.17%',
      top: '18.83%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '18.5%',
      top: '62.83%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '62.5%',
      top: '82.17%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '80.5%',
      top: '38%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '90.46%',
      height: '0.83%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '50.33%',
      rotate: '-22.5deg',
      backgroundColor: '#ffffff96',
      outlineColor: 'black',
    },
  },
  {
    type: 'text',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      fontSize: '6.67cqi',
      position: 'absolute',
      left: '16.01%',
      top: '9.86%',
      rotate: '-22.5deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'new north' },
  },
]
