import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=GxwcACwKbBfaKC6RfHvMJiU4u3zIS3AoDen2Pqn6JD4-0SQwiVk1hDuiSAiQq8rY0QSo6OgWKuZfZXBejAMvZSmLSak-P2NGAGAiRxpgJM0vJs8oq2v_a79X-_JPwkK-zAZUjCSWVFxbHN-XG9oXBNmoWiD55-wvszoF9rWZqtoK6SJkZVSGqwV6qqULYi9ryw9YGv8tofXle_4r-19ZUHquGb9yJ9vWQnyU1aLnD3tkiaVyWQHsI5uZWr5Qz2G7pbW7j4ywjNXS6l_3zqAZmSEpitihqL_sQE1s7B4pL6fxhRuGWbTPG1G6msCebyex2jrt9WRRwHY7W_XIY0O8d1amUim2bTVkbarUKO7aDLmnqZI3pH0h6IYnamLWHUj9-QA7Sx9ZUp6kqO_UJEDLhNtf1yxISGZCOYFXFtdz77n9pR83_439UKMYZu99eTT4bdWU9G_p_yHG-V8kS3ke1PPh7P5riIeTa1bKRwyhub9IfbMDSTKVPDyO99yiG7McUfbpwby-DPvsrKl-eqFgDwsS7gF9Ow2ZWJr6Mzj-4w2aleiCA83m7hkQdQRZYPbmGhKVYculGwbit567qfWIsu8H9DhIVr0c9aH4IGTGtqTelp554AWZTEL4HOc9xL4gyLcL7Wu2m9i4TWv2P0YsXT5fNWEHrGfGAD_ZcV_D54tCyY_AJ3MrxwF2NvB68WfnLd5gO7UW9rWMnSqJZPF7dREIYF-5JmAcC9lZru2Ym9xm3DK53sjr_dCd_e0gwKw7O27oeHTJrGmqcirpMVXM8-W80V2-n4xLbj-Peg_JAQtvyh0np6A1bzWxlZvufVDPRZ_oWWIAJQApqb9nE2vdWIhTOE7GiPFaVg_77m1JvRYcD7VBbhSdpP151FeS7MuCmzp_okjF02kltBwf5JqTSFlfoq3lRwTX9dA0hLATvySv5oruziPb2N_snqHVgTSEO_T7PHixjeGQp_qg0cmHHzeBLIoL1Qf9w8VXxSRxybsXqL6XG_YuAEGJEse6tYZVu4KZLwyA15CzR5tZn9zeWJNZEdzQf9lwt_LVh9K5RnlMSAfCxwP0OHBph09nnclSwEXms5T1BUuBj3L5F5bnLKYETEQiopEfCxG3mbW8WAhvr0Piw0LFivkwj7UdCnXrzs72YKeJMTthIZIOLpwiVgkFUU4-DFbU2yJwvtNBiQI-OyVCua1h5lcQWYe885PW0EYac1k8Y7WGM5KUc8CA1tpBfgWxUjrTqUA6dQKBO2LATGXujk54KOdznd5jxwgPjmCda5wHK7MRk9HzrKQMLCbw1mRYCvecOka4dyRIWop8VHywuUJWc-v8P1WIOQyVvWJXUrETCEjIWWcBzhqGSG0vQzoegiibfHmPA0KiNylEPAcslL1OhckTPEQ87xM9BywShSoJPQf0E4LFEvIMVtQ7IoQsoZQnDugvSvEwoUgBdz_QbzzpCnm-jxEsl-FydFNoB8EnrCxRLgtM6AKP2UVXHPA7nfW2W0edrwpRd7GSqcu63XSdi8POmvIH1onmgXaXLqUT1i_mFdEi2Uyp0OoEQusRHJLQyQEtIp-7yomqovBK5rorDt8JhDUfTPS2FenL_6t3c01gvSyl8gW9dpEB_Jt05hgr2hi-STEH3b5jhC1aIZPFxCVWEKyMeb1QsRMIp0RufrktR3A1AK4KnggVHQX8MdahA5anQb4fWt4XGkedBdom42KUXG-PaLTJrBg4ZC9abS4oBh8qBpMRHhYDfQyDc0zeTHiCfOKVha-ajPOKhfLKxpAfj_N7MmVpGBX6AQ

export const rb3RaidplanAnim: WaapiEntity[] = [
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '40.17%',
      top: '45.83%',
      width: '13.33%',
      rotate: '112.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '54.17%',
      top: '40%',
      width: '13.33%',
      rotate: '-157.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '19.5%',
      top: '63.67%',
      rotate: '62.28deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.5%',
      top: '19%',
      rotate: '157.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '81.17%',
      top: '37.33%',
      rotate: '-112.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'rect',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      width: '19.33%',
      height: '19.33%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '63.17%',
      top: '81.83%',
      rotate: '-22.5deg',
      backgroundColor: '#c77f7da6',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '60%',
        top: '60.33%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '60%', offset: 0.3, top: '60.33%' },
      { left: '56.33%', offset: 0.4, top: '63.33%' },
      { offset: 1, opacity: 1, left: '56.33%', top: '63.33%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '60%',
      top: '60.33%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '64.83%',
        top: '35.67%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '64.83%', offset: 0.3, top: '35.67%' },
      { left: '64.33%', offset: 0.5, top: '55.67%' },
      { offset: 1, opacity: 1, left: '64.33%', top: '55.67%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '64.83%',
      top: '35.67%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '34.67%',
        top: '35.5%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '34.67%', offset: 0.3, top: '35.5%' },
      { left: '43.5%', offset: 0.4, top: '35%' },
      { offset: 1, opacity: 1, left: '43.5%', top: '35%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '34.67%',
      top: '35.5%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '38.67%',
        top: '60.17%',
        width: '7.65%',
        height: '7.65%',
        rotate: '0deg',
        borderRadius: '50%',
        backgroundColor: '#ff7676',
        outlineColor: 'black',
        offset: 0,
      },
      { opacity: 0, offset: 0.2 },
      { opacity: 1, offset: 0.25 },
      { left: '38.67%', offset: 0.3, top: '60.17%' },
      { left: '44.5%', offset: 0.4, top: '62.83%' },
      { offset: 1, opacity: 1, left: '44.5%', top: '62.83%' },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '38.67%',
      top: '60.17%',
      width: '7.65%',
      height: '7.65%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ff7676',
      outlineColor: 'black',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '46%',
        top: '60.17%',
        width: '13.33%',
        rotate: '22.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '46%',
      top: '60.17%',
      width: '13.33%',
      rotate: '22.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '45.67%',
        top: '39.83%',
        width: '13.33%',
        rotate: '157.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.67%',
      top: '39.83%',
      width: '13.33%',
      rotate: '157.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '60.5%',
        top: '54.67%',
        width: '13.33%',
        rotate: '-67.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '60.5%',
      top: '54.67%',
      width: '13.33%',
      rotate: '-67.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'triangle',
    duration: 4000,
    keyframes: [
      {
        opacity: 0,
        fill: '#c57d7aa6',
        position: 'absolute',
        translate: '-50% -50%',
        left: '54.33%',
        top: '60.67%',
        width: '13.33%',
        rotate: '-22.5deg',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.75 },
      { opacity: 1, offset: 0.8 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fill: '#c57d7aa6',
      position: 'absolute',
      translate: '-50% -50%',
      left: '54.33%',
      top: '60.67%',
      width: '13.33%',
      rotate: '-22.5deg',
      scale: '1 1',
    },
  },
  {
    type: 'melee',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '59.83%',
        top: '60.33%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '59.83%', offset: 0.3, top: '60.33%' },
      { left: '56.33%', offset: 0.4, top: '63.5%' },
      { offset: 1, left: '56.33%', top: '63.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '59.83%',
      top: '60.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '38.67%',
        top: '60.17%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '38.67%', offset: 0.3, top: '60.17%' },
      { left: '44.33%', offset: 0.4, top: '62.83%' },
      { offset: 1, left: '44.33%', top: '62.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '38.67%',
      top: '60.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '34.67%',
        top: '35.17%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '34.67%', offset: 0.3, top: '35.17%' },
      { left: '43.33%', offset: 0.4, top: '34.83%' },
      { offset: 1, left: '43.33%', top: '34.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '34.67%',
      top: '35.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'ranged',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '64.67%',
        top: '35.5%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '64.67%', offset: 0.3, top: '35.5%' },
      { left: '64.33%', offset: 0.5, top: '55.83%' },
      { offset: 1, left: '64.33%', top: '55.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '64.67%',
      top: '35.5%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '70.17%',
        top: '50%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '70.17%', offset: 0.3, top: '50%' },
      { left: '76%', offset: 0.4, top: '40.83%' },
      { offset: 1, left: '76%', top: '40.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '70.17%',
      top: '50%',
      rotate: '0deg',
    },
  },
  {
    type: 'healer',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '29.17%',
        top: '49.83%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '29.17%', offset: 0.3, top: '49.83%' },
      { left: '24.17%', offset: 0.45, top: '60.5%' },
      { offset: 1, left: '24.17%', top: '60.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '29.17%',
      top: '49.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.33%',
        top: '37.17%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '50.33%', offset: 0.3, top: '37.17%' },
      { left: '39.17%', offset: 0.45, top: '26.17%' },
      { offset: 1, left: '39.17%', top: '26.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.33%',
      top: '37.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 4000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '49.83%',
        top: '65.17%',
        rotate: '0deg',
        offset: 0,
      },
      { left: '49.83%', offset: 0.3, top: '65.17%' },
      { left: '60.17%', offset: 0.45, top: '74.17%' },
      { offset: 1, left: '60.17%', top: '74.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '49.83%',
      top: '65.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.17%',
      top: '18.83%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '18.5%',
      top: '62.83%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '62.5%',
      top: '82.17%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
  {
    type: 'circle',
    duration: 4000,
    keyframes: [],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '80.5%',
      top: '38%',
      width: '5%',
      height: '5%',
      rotate: '0deg',
      outlineWidth: '0.67cqi',
      outlineOffset: '-0.33cqi',
      outlineStyle: 'solid',
      borderRadius: '50%',
      backgroundColor: '#3ccfff05',
      outlineColor: '#89ebff',
    },
  },
]
