import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=G4EaQGT-3TQ4001tqgLR1uMQtYEYMQMKP2PF5vMtJm_v2usYcqqr6Kz-f_ulQH__CwsTHqUDkxNhqO0sCNPjc-ZN8GdDKBNVYUgt3JkSKqA3LRtb1wpXaaprVWR1WVqU1l-Z0QqwF-Or-4s9Hf4ZoT9abFFZJsEkKPoddGK5kojUdHG5p8aAPNWzaZcqLma9464V27lf72Pn9GYz1xV-BZf5ATxSBgN4qFXMMe26CzXCt-eBnydeuNVF7E8v7Rxo9Qx76pvq8M8zXUPaV6PRhPCEWPRxDuX3woNNK15YqnGn0ASjF823GTYoCEW58Y84Ko3q2OlaPevPfoJ2a7UeXm4u6a_KvHCrDIRbjWIwkmDp04Fkhfn1xTTJ7dcZwNuHUjqQdPjqDOD7ZSDcKG0MwdkH3nailEpVSLwjPIEO_mVHFjLzSAmdlS_LmkvZW3L8RYQnKC2KzuvSVZ2jwxZab_tBrUiFmWPXRgYvuWJNWnjsCk_jn9XT4k_6cwb1hS3r15VGfl_-pCrF_IYp5lJU8yoiiUrGx7tX_qHKbK81xSftNof1Mz16QVZuwyyeyP-onqHSVOzvXMunO8L__XpMv3xB944Lelk9_Z92R8eWZkcRVhmmwrhzrVZf-Oyn_DHp2IUtX78M4xFjQU3Xpv9I85fxiUfs5iTEfyI82X8OggZsA1v9XOmRfkPhTkKHswj5A2JEkrfLZsNQfHVeeO96GRxYPPMPtpCvRVQXHmut4syOs_dEx2K2onBaR_gmgia7Ng3o5yftMRCJf6o_F_NN56svD5VBf46TCYIgDKy6rm50jBmR5-QXCjdLEOLecIJO5M8UdlRzZk30lnaKAtFiMFMF9plWzmWFjL403Ad4TWill45rtTLyrD-3B3pn9SIzg6kqLnPHXc3mB4IKGmcK3rt2awlhFC8YiVEIUi5anHBjVQivPpFbkOLUnb1333fd24oYFse2OGJKrUxFOSjz5mVCp3LYE54eXsmk3axJwekAxg9GDwhr7827w6A1I0FoTRqAcGUKoVo3KoeIu9LO82GX7kNQ-x1ozg1aISCSCRturH9LvzwWVGr670R5QZr20h-xoIQ1GvsCZb7Z6Wh0JGGQ0jQArRiVapx5AB6kj2ZUXg00AC0LmJkshAP3igghTqX1WxS7wpO9oE3Pi1g46KjgydsVNABVUkJk3qzqGbhPtBZNIpEUTQPQEaOhoDben7ePnhmMWcaENRMdFzMRURB4UhO1GRUdOZwS9eQ0pfUQgwqhdNCVwSHWeIWFY5ir0UNQlcURpV1lFgIqISecrmwMAYEr5SxewkMDfRQKSlbJwkExIZLRR6MCS9H_aExTKO5wCJoMp4givnaQX4jYMDkNXt_pm-Dk5qVRx6WoFNOP6MU7HAIe4-0RxxMLeaJkGFHsNABF4xqbWtNMAIgx5nIGDNcSdEljMuQIGPQ-Klbq3KzJAf0USF_efoWV6LdA50ueLQz6JTJYhLLOf8gVrYoRTM6fKho50tbE_hDF-MhIi_mjIJc7561OoQVZQjFnNUU0i5lMOHCIam_QEHgcymJ0W93MNESqFEXmIE_F5wUKE9nNbv7pB7cryGFCuGqvFM77TG6WGQLK5Evr3ewwBNUQlJIpLPmRXCh45OM0GLSzxapQwzlUanmazGQjx2D8pGB5Ws0wSDMKY_20wbpjJmZgV9PAdjdn_YARV9CUNKy1wSCx2WvJJwEazRiyEYnINweIcWXJ4p8_tSCf16ao7tWCQkoSRoKU_Vbk6y9r-wA

export const diHectorMeleeAnim: WaapiEntity[] = [
  {
    type: 'checkerboard',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.17%',
        top: '49.83%',
        width: '80%',
        height: '80%',
        rotate: '0deg',
        backgroundSize: '20cqi 20cqi',
        backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { opacity: 0, offset: 0.5 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '49.83%',
      width: '80%',
      height: '80%',
      rotate: '0deg',
      backgroundSize: '20cqi 20cqi',
      backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
      scale: '1 1',
    },
  },
  {
    type: 'checkerboard',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.33%',
        top: '49.83%',
        width: '80%',
        height: '80%',
        rotate: '90deg',
        backgroundSize: '20cqi 20cqi',
        backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.33%',
      top: '49.83%',
      width: '80%',
      height: '80%',
      rotate: '90deg',
      backgroundSize: '20cqi 20cqi',
      backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
      scale: '1 1',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '25%',
      top: '25%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '25.17%',
      top: '74.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '75%',
      top: '24.67%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '74.83%',
      top: '74.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '35%',
      top: '54.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '55%',
      top: '64.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.17%',
      top: '35%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '65%',
      top: '44.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '35.17%',
        top: '54.83%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '35.17%', offset: 0.43, top: '54.83%' },
      { opacity: 0, offset: 0.45, left: '65.17%', top: '54.83%' },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '65.17%', top: '54.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '35.17%',
      top: '54.83%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '44.83%',
        top: '64.83%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '44.83%', offset: 0.43, top: '64.83%' },
      { opacity: 0, offset: 0.45, left: '55.17%', top: '64.67%' },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '55.17%', top: '64.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '44.83%',
      top: '64.83%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '65.17%',
        top: '44.67%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '65.17%', offset: 0.43, top: '44.67%' },
      { opacity: 0, offset: 0.45, left: '35.33%', top: '45.17%' },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '35.33%', top: '45.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '65.17%',
      top: '44.67%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '55%',
        top: '35%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '55%', offset: 0.43, top: '35%' },
      { opacity: 0, offset: 0.45, left: '44.83%', top: '35%' },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '44.83%', top: '35%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '55%',
      top: '35%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '8.33cqi',
        position: 'absolute',
        left: '6.17%',
        top: '1.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { opacity: 0, offset: 0.5 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '8.33cqi',
      position: 'absolute',
      left: '6.17%',
      top: '1.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '1 possible configuration' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '8.33cqi',
        position: 'absolute',
        left: '6%',
        top: '1.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '8.33cqi',
      position: 'absolute',
      left: '6%',
      top: '1.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '2 possible configuration' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '31.14%',
        top: '61.93%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '31.14%', offset: 0.43, top: '61.93%' },
      { left: '30.97%', offset: 0.45, top: '41.76%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '30.97%', top: '41.76%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '31.14%',
      top: '61.93%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'MT/M1' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '52.17%',
        top: '32.5%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '52.17%', offset: 0.43, top: '32.5%' },
      { left: '51.5%', offset: 0.45, top: '53%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '51.5%', top: '53%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '52.17%',
      top: '32.5%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'OT/M2' },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '63%',
        top: '39.33%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '63%', offset: 0.43, top: '39.33%' },
      { left: '41.67%', offset: 0.45, top: '40%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '41.67%', top: '40%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '63%',
      top: '39.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '37.17%',
        top: '59.83%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '37.17%', offset: 0.43, top: '59.83%' },
      { left: '57.33%', offset: 0.45, top: '59.67%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '57.33%', top: '59.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '37.17%',
      top: '59.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '42.33%',
        top: '59.83%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '42.33%', offset: 0.43, top: '59.83%' },
      { left: '62%', offset: 0.45, top: '59.67%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '62%', top: '59.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '42.33%',
      top: '59.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '57.83%',
        top: '39.33%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '57.83%', offset: 0.43, top: '39.33%' },
      { left: '36.83%', offset: 0.45, top: '39.83%', opacity: 0 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '36.83%', top: '39.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '57.83%',
      top: '39.33%',
      rotate: '0deg',
    },
  },
]
