import { WaapiEntity } from '@/components/animated-schematic'

// http://localhost:3000/?s=G_YgQGRIZ2qlBKjEAirLLBmhYBKgSfJb5zHAW8ub-8Tbr6XJp-Ba3GjFKX7_y3f2ZScNLDKcUQb3q8X13RWG43P2TerLN2lFQRemqew_M49S-k1pmqqqA-GQBi0jsWlpN9uT_oo0CwY3fG3q6JYc_zNCf3V0Te65uqvLzo-Bp49_rUtLCY2rLblgIG_pNCGPTjO2kdxC2Pi3y3nslHN2tZ8VfheYeT6CzoCPvLY26rt-nQismG-yhjzn68haFil-emn85rWcUex739rwP890AVt_TlEqhHso8uME79-L3auWXZeJVROkwuHd1vjqS4XEUGvlH3EsV6rzu-6TJ-fv_h54jy7l8Nbqmf5p5sHPZgB-tjJqS_rYecSQXsKhbagx9_mr-Mg3a54lzOqeGB_5dgbgJ_mqmDC-5W8SkWc40qHG4RXUImwsumDzSMRaTmzsODvt3dxdjwKvIF8c5xPJyVru6Ms5ycIOSyO5627dZwJy5mUlqf8xDq8uE-hytfiL-Xup6JMH-b9OrNTvX5q_99Fk5_7pb4kq5g_uqG_Kq89htEIHg5sf-B-qDDdok0ezWCjN-8jra-eJIfGDGFQvFvJxaxSxm07aJrcGhRb_E3hl2S93hXLRKToAnZLqfBx-vIzR4ltPir3mSXFhuVmc3zh85GRF4yoFa5-gDz7Isi1bsiwk2a-HcZv-bEO3bEQHjOd95Ie1oa-tuSwmBGPJRBsxb6fpQZG9PrLs5Y22NcM7L8zAzaf3_OkDbDSi3PUYXeueFS3tDfHW2GuR3kmIjUpIteebgGffLKrgG_P33nenv8V37p9dv-q9wf8QQuhrddFyunQkjalQ_cnsszQmLvjI-WLSVmxHth48D7OgW-7uG2nbh1l52er31FfW9SIJSyw7LvRE4faSUb40bLsXnyTcWjaiGBHHtnM3PnF4PJNk3xGD5e1GMwD_OSZWXw4jTP7aiH7WVR_uljfvIxf3rLQUsNwbb9RHttaMrKJWcU-8SR_ZXLNPyZHUOLwm8I4flOo8jIrZ8-3tnU1nlSvWTRkoo7YdU-6tnTjFDu1koDkFhAizkD64jS4FpSfn710feIflkDUgVNbYqiYRoA0USBV0h_XrrpMFurgwVFJHoQBXHEqXnm-MVK1xssAI1PEbvnxf9xVSEYRGlOeVwnE2QpmeeeoF2EAJJuHV9aWuVWVVBQs-gq6c6eBx6XnHsAbHea8rHdMY1INKeF-61xEAm3pBUNZu_5eo7bBM8wy5IWOl0g7QpsdpZcUZNXj0-oqonmJoNQA6gYhsc6ikURbQZCs5aTEBryxA4rMRM-pBJ4GBSSbNmimhLZFt6IsLjNsRJ0F6Cqz1Y1Nb68Ed3GlL5BMj1zLRVQkJaGJQOVdSHAkgYoB1TixLeBMDYDLt51KprnToYzAMj8MsPYgGkp1UrKIWRftAjQ1Hsx7EgJg9CVlRn2lpA0gFgqPpQa-B8oRnzK6XRT-AJJqkZiugS0iygvZKCeZDKCHPToXpSbPgZTsgJaCo1-xIVan26-UCmirXUctlCsxSrm0OPWC03k4ZXg_Opat5ic5jFERIZtseVd-fYYIsZiUGt0HmVKUMNimnigWvkZFIOwY407CSEiHHoB6jzTRNXcmi82BY44I0PYgG40iNS51W1tBYgScfc-ISXlUwNLbgAXsSTSprLyRQC09zUu3UVI16IVR2OwwxTVFJPWXVRSIZqawnDinvNuDKVDMk9NGDDgELzxA0PegKW5GOIoGduv2ha8ClrC5LDzrgjNmvSvytB30CGLFWp-lBGVZpMyQjGnrQjQCvxDqzuhdIxzlDOg0ZxtCDbgKxqBuetQjqxkw1JsrgllZSWJiBJ0k1kjpB9DcMZUKSY-0VE6YwoZP1zFTm8BIvAxcxwGRuHJJhlRhgzI3bMmYXA-xkRkUZiIsBzNNoLmuZgdksrWYVMyDhBivFxo6VveakkNPa1qCSo-nuFQsLZohWFQQNQB3SaNq0ksJoWjGDq4BUCQjoH1yKsvGMqUwQfbwi6zQNWg2A0isDEbdrNwXolpU7IyIOBZYurklD_qM3Ag

export const diRaidplanMeleeAnim: WaapiEntity[] = [
  {
    type: 'checkerboard',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.17%',
        top: '49.83%',
        width: '80%',
        height: '80%',
        rotate: '0deg',
        backgroundSize: '20cqi 20cqi',
        backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { opacity: 0, offset: 0.5 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 1,
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.17%',
      top: '49.83%',
      width: '80%',
      height: '80%',
      rotate: '0deg',
      backgroundSize: '20cqi 20cqi',
      backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
      scale: '1 1',
    },
  },
  {
    type: 'checkerboard',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        position: 'absolute',
        translate: '-50% -50%',
        left: '50.33%',
        top: '49.83%',
        width: '80%',
        height: '80%',
        rotate: '90deg',
        backgroundSize: '20cqi 20cqi',
        backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
        scale: '1 1',
        offset: 0,
      },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      position: 'absolute',
      translate: '-50% -50%',
      left: '50.33%',
      top: '49.83%',
      width: '80%',
      height: '80%',
      rotate: '90deg',
      backgroundSize: '20cqi 20cqi',
      backgroundImage: 'repeating-conic-gradient(#ffffff00 0% 25%, #ff000054 0% 50%)',
      scale: '1 1',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '25%',
      top: '25%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '25.17%',
      top: '74.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '75%',
      top: '24.67%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '74.83%',
      top: '74.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '35%',
      top: '54.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '55%',
      top: '64.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '45.17%',
      top: '35%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'circle',
    duration: 6000,
    keyframes: [],
    initialValues: {
      opacity: 0.75,
      position: 'absolute',
      translate: '-50% -50%',
      left: '65%',
      top: '44.83%',
      width: '8.33%',
      height: '8.33%',
      rotate: '0deg',
      borderRadius: '50%',
      backgroundColor: '#ffffff',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '20.31%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '35.17%',
        top: '50.17%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '35.17%', offset: 0.43, top: '50.17%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '35.17%', top: '50.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '20.31%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '35.17%',
      top: '50.17%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '20.31%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50%',
        top: '64.83%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '50%', offset: 0.43, top: '64.83%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '50%', top: '64.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '20.31%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50%',
      top: '64.83%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '9.42%',
        height: '20.31%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '65%',
        top: '50.17%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '65%', offset: 0.43, top: '50.17%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '65%', top: '50.17%' },
    ],
    initialValues: {
      opacity: 1,
      width: '9.42%',
      height: '20.31%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '65%',
      top: '50.17%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'rect',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '20.31%',
        height: '9.42%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '50%',
        top: '35%',
        rotate: '0deg',
        outlineWidth: '0.83cqi',
        outlineOffset: '-0.42cqi',
        outlineStyle: 'solid',
        backgroundColor: '#ffffff00',
        outlineColor: '#16f600',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '50%', offset: 0.43, top: '35%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '50%', top: '35%' },
    ],
    initialValues: {
      opacity: 1,
      width: '20.31%',
      height: '9.42%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '50%',
      top: '35%',
      rotate: '0deg',
      outlineWidth: '0.83cqi',
      outlineOffset: '-0.42cqi',
      outlineStyle: 'solid',
      backgroundColor: '#ffffff00',
      outlineColor: '#16f600',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '24.5%',
        top: '51.67%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '24.5%', offset: 0.43, top: '51.67%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '24.5%', top: '51.67%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '24.5%',
      top: '51.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '29.5%',
        top: '51.83%',
        rotate: '0deg',
        offset: 0,
      },
      { top: '51.83%', offset: 0.38 },
      { opacity: 1, offset: 0.42 },
      { left: '29.5%', offset: 0.43, top: '51.83%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, top: '51.83%', opacity: 1, left: '29.5%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '29.5%',
      top: '51.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '75.5%',
        top: '49.83%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '75.5%', offset: 0.43, top: '49.83%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '75.5%', top: '49.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '75.5%',
      top: '49.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '71%',
        top: '49.83%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '71%', offset: 0.43, top: '49.83%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '71%', top: '49.83%' },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '71%',
      top: '49.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '8.33cqi',
        position: 'absolute',
        left: '6.17%',
        top: '1.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { opacity: 0, offset: 0.5 },
      { offset: 1, opacity: 0 },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '8.33cqi',
      position: 'absolute',
      left: '6.17%',
      top: '1.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '1 possible configuration' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 0,
        fontSize: '8.33cqi',
        position: 'absolute',
        left: '6%',
        top: '1.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 0, offset: 0.42 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 0,
      fontSize: '8.33cqi',
      position: 'absolute',
      left: '6%',
      top: '1.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '2 possible configuration' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '18.3%',
        top: '45.26%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '18.3%', offset: 0.43, top: '45.26%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '18.3%', top: '45.26%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '18.3%',
      top: '45.26%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'MT/M1' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '66%',
        top: '51.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '66%', offset: 0.43, top: '51.67%' },
      { opacity: 1, offset: 0.45 },
      { opacity: 1, offset: 0.5 },
      { offset: 1, opacity: 1, left: '66%', top: '51.67%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '66%',
      top: '51.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'OT/M2' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '19.67%',
        top: '40.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { left: '19.67%', offset: 0.43, top: '40.67%' },
      { left: '45.33%', offset: 0.45, top: '17.33%' },
      { offset: 1, left: '45.33%', top: '17.33%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '19.67%',
      top: '40.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '(long)' },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '53.67%',
        top: '28.83%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '53.67%',
      top: '28.83%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '49%',
        top: '28.67%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '49%',
      top: '28.67%',
      rotate: '0deg',
    },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '43.67%',
        top: '22%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '43.67%', offset: 0.43, top: '22%' },
      { offset: 1, opacity: 1, left: '43.67%', top: '22%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '43.67%',
      top: '22%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'MT/M1' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '43.83%',
        top: '17.17%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '43.83%', offset: 0.43, top: '17.17%' },
      { left: '19%', offset: 0.45, top: '40.83%' },
      { offset: 1, opacity: 1, left: '19%', top: '40.83%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '43.83%',
      top: '17.17%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '(short)' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '67.33%',
        top: '55.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '67.33%', offset: 0.43, top: '55.67%' },
      { left: '44.17%', offset: 0.45, top: '77.17%' },
      { offset: 1, opacity: 1, left: '44.17%', top: '77.17%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '67.33%',
      top: '55.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '(long)' },
  },
  {
    type: 'melee',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '52.33%',
        top: '71.33%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '52.33%',
      top: '71.33%',
      rotate: '0deg',
    },
  },
  {
    type: 'tank',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        width: '5%',
        height: '5%',
        position: 'absolute',
        translate: '-50% -50%',
        left: '47.5%',
        top: '71.17%',
        rotate: '0deg',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { offset: 1, opacity: 1 },
    ],
    initialValues: {
      opacity: 1,
      width: '5%',
      height: '5%',
      position: 'absolute',
      translate: '-50% -50%',
      left: '47.5%',
      top: '71.17%',
      rotate: '0deg',
    },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '42.33%',
        top: '73.33%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '42.33%', offset: 0.43, top: '73.33%' },
      { offset: 1, opacity: 1, left: '42.33%', top: '73.33%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '42.33%',
      top: '73.33%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: 'OT/M2' },
  },
  {
    type: 'text',
    duration: 6000,
    keyframes: [
      {
        opacity: 1,
        fontSize: '5cqi',
        position: 'absolute',
        left: '43%',
        top: '77.67%',
        rotate: '0deg',
        scale: '1 1',
        transformOrigin: 'top left',
        lineHeight: 0.77,
        color: '#ffffff',
        offset: 0,
      },
      { opacity: 1, offset: 0.42 },
      { left: '43%', offset: 0.43, top: '77.67%' },
      { left: '67.17%', offset: 0.45, top: '55.5%' },
      { offset: 1, opacity: 1, left: '67.17%', top: '55.5%' },
    ],
    initialValues: {
      opacity: 1,
      fontSize: '5cqi',
      position: 'absolute',
      left: '43%',
      top: '77.67%',
      rotate: '0deg',
      scale: '1 1',
      transformOrigin: 'top left',
      lineHeight: 0.77,
      color: '#ffffff',
    },
    specialValues: { text: '(short)' },
  },
]
